import { c as create_ssr_component } from './ssr.js';
const metadata = {
  title: 'Using JavaScript Libraries with Svelte',
  author: 'Ronald Otieno',
  date: '2023-10-29T00:00:00.000Z',
  layout: 'blog',
  published: true,
  excerpt:
    'Learn the techniques of using any JavaScript library in a Svelte app and most importantly discover the super powers hidden inside Svelte Actions.'
};
const Usingu20jsu20librariesu20withu20svelte = create_ssr_component(
  ($$result, $$props, $$bindings, slots) => {
    return `<h2 id="introduction" data-svelte-h="svelte-p88ani">Introduction</h2> <p data-svelte-h="svelte-18f3tux">When using JavaScript libraries, the most important thing to do is usually to get a DOM reference that the library can interact with.
In vanilla JavaScript projects, this is normally easy by using the native API’s such <code>querySelector</code> or <code>getDocumentById</code>. But when working with frameworks such as Svelte, Vue or React, different methods are use to get reference to the DOM. In Svelte we use <code>bind:this</code> directive.
In this article I will go through different methods of using any JavaScript library in your Svelte app.</p> <h2 id="onmount-lifecycle" data-svelte-h="svelte-1gsro0p">onMount lifecycle</h2> <p data-svelte-h="svelte-oydlj2">The onMount is a lifecyle function designed for executing code when a component is first mounted in the DOM.</p> <p data-svelte-h="svelte-1fkbebb">Code written within the onMount block runs only once when the component is initially rendered. Allowing for actions such as fetching data, initializing variables, or interacting with DOM immediately after the component is mounted.</p> <h3 id="example-with-motion-one-animation-library" data-svelte-h="svelte-1u0nj37">Example with Motion One Animation Library</h3> <p data-svelte-h="svelte-1753hav">In this example we be using an animation library called (Motion One)[https:///motion.dev “Motion One website”].</p> <h3 id="install-the-library" data-svelte-h="svelte-1n2bxce">Install the library</h3> <p data-svelte-h="svelte-1nhf661"><code>npm install motion</code></p> <h3 id="import-and-use-the-libarary" data-svelte-h="svelte-bynags">Import and use the libarary</h3> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F8F8F2">&lt;</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">import</span><span style="color: #F8F8F2"> &#123;onMount&#125; </span><span style="color: #F92672">from</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;svelte&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">import</span><span style="color: #F8F8F2"> &#123;animate, stagger&#125; </span><span style="color: #F92672">from</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;motion&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #88846F">//wait for the DOM to load</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #A6E22E">onMount</span><span style="color: #F8F8F2">(()</span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2">&#125;&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">                const letters </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> document.</span><span style="color: #A6E22E">querySelectorAll</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;.letter&#39;</span><span style="color: #F8F8F2">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">                </span><span style="color: #A6E22E">animate</span><span style="color: #F8F8F2">(</span></span>
<span class="line"><span style="color: #F8F8F2">                    </span><span style="color: #FD971F; font-style: italic">letters</span><span style="color: #F8F8F2">,</span></span>
<span class="line"><span style="color: #F8F8F2">                    &#123;color: </span><span style="color: #E6DB74">&#39;orangered&#39;</span><span style="color: #F8F8F2">, y: [</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">, </span><span style="color: #AE81FF">30</span><span style="color: #F8F8F2">, -</span><span style="color: #AE81FF">60</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">], rotate: </span><span style="color: #AE81FF">360</span><span style="color: #F8F8F2">&#125;,</span></span>
<span class="line"><span style="color: #F8F8F2">                    &#123;duration: </span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">, delay: </span><span style="color: #FD971F; font-style: italic">stagger</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">0.1</span><span style="color: #F8F8F2">), repeat: </span><span style="color: #FD971F; font-style: italic">Infinity</span><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"><span style="color: #F8F8F2">                       )</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            &#125;)</span></span>
<span class="line"><span style="color: #F8F8F2">&lt;/</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">&lt;</span><span style="color: #F92672">div</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letters flex gap-0.5 text-6xl font-semibold uppercase&quot;</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">    &#123;#</span><span style="color: #F92672">each</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Svelte&#39;</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">split</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">as</span><span style="color: #F8F8F2"> letter&#125;</span></span>
<span class="line"><span style="color: #F8F8F2">        &lt;</span><span style="color: #F92672">span</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letter inline-block&quot;</span><span style="color: #F8F8F2">&gt; </span><span style="color: #F92672">&#123;</span><span style="color: #F8F8F2">letter</span><span style="color: #F92672">&#125;</span><span style="color: #F8F8F2">&lt;/</span><span style="color: #F92672">span</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">    &#123;/</span><span style="color: #F92672">each</span><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"><span style="color: #F8F8F2">&lt;/</span><span style="color: #F92672">div</span><span style="color: #F8F8F2">&gt;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-oschm7">This method works but there is a catch. As your app grows the complexity becomes difficult to manage.
And also this is not the svelte way of doing things.
The Svelte way of handling the DOM is by using the <code>bind</code> directive to gain reference to an element instead of querying the DOM yourself.</p> <h2 id="dynamic-import" data-svelte-h="svelte-oi210p">Dynamic Import</h2> <p data-svelte-h="svelte-peakxr">In Svelte, dynamic imports allow for the asynchronous loading of components or other modules when they’re need, rather than at the initial page load.</p> <p data-svelte-h="svelte-137drfv">Using the <code>import()</code> function, you can load components or modules on demand.</p> <p data-svelte-h="svelte-18llx1n">This helps in optimizing perfomance by fetching code only when required, enabling faster initial page loads.</p> <p data-svelte-h="svelte-lyj6ec">Here is an example of dynamically importing a JavaScript module.</p> <p data-svelte-h="svelte-cskbm1">Let’s assume you have a JavaScript module named <code>mathUtils.js</code> with some basic Mathematics utility functions:</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F92672">export</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">add</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">a</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">b</span><span style="color: #F8F8F2">)&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> a</span><span style="color: #F92672">+</span><span style="color: #F8F8F2">b;</span></span>
<span class="line"><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"><span style="color: #F92672">export</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">subtract</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">a</span><span style="color: #F8F8F2">,</span><span style="color: #FD971F; font-style: italic">b</span><span style="color: #F8F8F2">)&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">return</span><span style="color: #F8F8F2"> a</span><span style="color: #F92672">-</span><span style="color: #F8F8F2">b;</span></span>
<span class="line"><span style="color: #F8F8F2">&#125;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-nvz3yi">In a Svelte component, you can import and use this module:</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F8F8F2">&lt;</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">    </span><span style="color: #F92672">async</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">loadMathModule</span><span style="color: #F8F8F2">()&#123;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">    &#125;</span></span>
<span class="line"><span style="color: #F8F8F2">&lt;/</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-pn08l7">Dynamically importing a moduling when interacting with a library will only avail the browser features, and DOM when required.
This will prevent the library code from running on the server during server side rendering whereby the library will try to access APIs such as the window object which is not available on the server.</p> <h2 id="disable-ssr" data-svelte-h="svelte-1m8luad">Disable SSR</h2> <p data-svelte-h="svelte-1718vgk">In Sveltekit, server-side-rendering (SSR) is enabled by default. However, there might be scenarios where you want to disable SSR for specific pages or components.</p> <p data-svelte-h="svelte-18um76g">To disable SSR, for a particular route or component, create a <code>+page.js</code> file for that particular route and add the following line of code.</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #88846F">//+page.js</span></span>
<span class="line"><span style="color: #F92672">export</span><span style="color: #F8F8F2"> </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> ssr </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> </span><span style="color: #AE81FF">false</span><span style="color: #F8F8F2">;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-1m1q9z4">In you add <code>export const ssr=false</code> to your root <code>+layout.js</code>, your entire app will only be rendered on the client which essentilly means your turn your app into a Single Page Application (SPA).</p> <p data-svelte-h="svelte-12jd7eu">Turning SSR off will enable your app to interact only with the browser API and avoid errors that will result when it tries to access browser features that are not available on the server.</p> <h3 id="using-the-bind-directive" data-svelte-h="svelte-123jgyd">Using the bind directive</h3> <p data-svelte-h="svelte-1q2tcpc">We can bind the letters to <code>letter</code> variable but there is a problem, there are more than one letters and therefore we should use an array of <code>letters</code>.
If we add index to the <code>each</code> loop block and we now access access every elements index at every iteration.</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #66D9EF; font-style: italic">let</span><span style="color: #F8F8F2"> letters </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> [];</span></span>
<span class="line"><span style="color: #F8F8F2">        $: console.</span><span style="color: #A6E22E">log</span><span style="color: #F8F8F2">(leteers)</span></span>
<span class="line"><span style="color: #F8F8F2">    &lt;/</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">    &#123;#</span><span style="color: #F92672">each</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Svelte&#39;</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">split</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">as</span><span style="color: #F8F8F2"> letter, i&#125;</span></span>
<span class="line"><span style="color: #F8F8F2">        &lt;</span><span style="color: #F92672">span</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">bind</span><span style="color: #F8F8F2">:</span><span style="color: #FD971F; font-style: italic">this</span><span style="color: #A6E22E">&#123;</span><span style="color: #F8F8F2">letters[i]</span><span style="color: #A6E22E">&#125;</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letter inline-block&quot;</span><span style="color: #F8F8F2">&gt; </span><span style="color: #F92672">&#123;</span><span style="color: #F8F8F2">letter</span><span style="color: #F92672">&#125;</span><span style="color: #F8F8F2">&lt;/</span><span style="color: #F92672">span</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">    &#123;/</span><span style="color: #F92672">each</span><span style="color: #F8F8F2">&#125;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-1do7sa2">And this is the Svelte way of interacting with the DOM.</p> <h3 id="using-svelte-actions" data-svelte-h="svelte-s3ouny">Using Svelte Actions</h3> <p data-svelte-h="svelte-1vn03mj">Svelte Action is simply a reusable piece of code that can be used to attach a certain behavior to an element.
This is the most efficient way because it is very reusable as you will see below.
Also note that svelte Actions are just regular functions that can be saved in a different JavaScript file and be imported as a utility.</p> <p data-svelte-h="svelte-1ei268s">We shall create a Svelte Action named <code>animateText</code> that will be able to animate the text the same way.
We get reference to the parent element <code>div</code> then access it’s children, <code>span</code> which we then animate.</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #F92672">import</span><span style="color: #F8F8F2"> &#123;animate, stagger&#125; </span><span style="color: #F92672">from</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;motion&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">animateText</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">element</span><span style="color: #F8F8F2">)&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">            </span><span style="color: #A6E22E">animate</span><span style="color: #F8F8F2">(</span></span>
<span class="line"><span style="color: #F8F8F2">                element.children,</span></span>
<span class="line"><span style="color: #F8F8F2">                </span><span style="color: #88846F">//[...element.children], //for typescript</span></span>
<span class="line"><span style="color: #F8F8F2">                &#123;color: </span><span style="color: #E6DB74">&#39;orangered&#39;</span><span style="color: #F8F8F2">, y: [</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">, </span><span style="color: #AE81FF">30</span><span style="color: #F8F8F2">, </span><span style="color: #F92672">-</span><span style="color: #AE81FF">60</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">], rotate: </span><span style="color: #AE81FF">360</span><span style="color: #F8F8F2">&#125;,</span></span>
<span class="line"><span style="color: #F8F8F2">                &#123;duration: </span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">, delay: </span><span style="color: #A6E22E">stagger</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">0.1</span><span style="color: #F8F8F2">), repeat: </span><span style="color: #AE81FF">Infinity</span><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">                   )</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">        &#125;</span></span>
<span class="line"><span style="color: #F8F8F2">    &lt;/</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">div</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">use</span><span style="color: #F8F8F2">:animateText </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letters&quot;</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">        &#123;#</span><span style="color: #F92672">each</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;Svelte&#39;</span><span style="color: #F8F8F2">.</span><span style="color: #A6E22E">split</span><span style="color: #F8F8F2">(</span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">) </span><span style="color: #F92672">as</span><span style="color: #F8F8F2"> letter, i&#125;</span></span>
<span class="line"><span style="color: #F8F8F2">            &lt;</span><span style="color: #F92672">span</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">bind</span><span style="color: #F8F8F2">:</span><span style="color: #FD971F; font-style: italic">this</span><span style="color: #A6E22E">&#123;</span><span style="color: #F8F8F2">letters[i]</span><span style="color: #A6E22E">&#125;</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letter inline-block&quot;</span><span style="color: #F8F8F2">&gt; </span><span style="color: #F92672">&#123;</span><span style="color: #F8F8F2">letter</span><span style="color: #F92672">&#125;</span><span style="color: #F8F8F2">&lt;/</span><span style="color: #F92672">span</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">        &#123;/</span><span style="color: #F92672">each</span><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"><span style="color: #F8F8F2">    &lt;/</span><span style="color: #F92672">div</span><span style="color: #F8F8F2">&gt;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-13vnkm1">The animation we work just as before.</p> <h3 id="improvement-of-svelte-actions-method" data-svelte-h="svelte-azbcl0">Improvement of Svelte Actions method</h3> <p data-svelte-h="svelte-1e3rfuv">We can take this a step further and encapsulate this entire logic into a Svelte Action function. Because when we have a reference to an element, we can do any sort of JavaScript action with it.</p> <p data-svelte-h="svelte-s6aye">First we grab the elements innerText and trim the whitespace just in case, then we split it. This is all pure JavaScript.
We then set it’s contents to empty.
Then we add each letter wrapped inside a <code>span</code> one by one to make them separate.</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #F92672">import</span><span style="color: #F8F8F2"> &#123;animate, stagger&#125; </span><span style="color: #F92672">from</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;motion&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">animateText</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">element</span><span style="color: #F8F8F2">)&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">            </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> text </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> element.innerTexx.</span><span style="color: #A6E22E">trim</span><span style="color: #F8F8F2">().</span><span style="color: #A6E22E">split</span><span style="color: #F8F8F2">();</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            element.innerText </span><span style="color: #F92672">=</span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            text.</span><span style="color: #A6E22E">forEach</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">letter</span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2">&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">                        element.innerHTML </span><span style="color: #F92672">+=</span><span style="color: #E6DB74">&#96;</span></span>
<span class="line"><span style="color: #E6DB74">                            &lt;span class=&quot;letter&quot;&gt;</span><span style="color: #F92672">$&#123;</span><span style="color: #F8F8F2">letter</span><span style="color: #F92672">&#125;</span><span style="color: #E6DB74">&lt;/span&gt;</span></span>
<span class="line"><span style="color: #E6DB74">                        &#96;</span></span>
<span class="line"><span style="color: #F8F8F2">                    &#125;)</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            </span><span style="color: #A6E22E">animate</span><span style="color: #F8F8F2">(</span></span>
<span class="line"><span style="color: #F8F8F2">                element.children,</span></span>
<span class="line"><span style="color: #F8F8F2">                </span><span style="color: #88846F">//[...element.children], //for typescript</span></span>
<span class="line"><span style="color: #F8F8F2">                &#123;color: </span><span style="color: #E6DB74">&#39;orangered&#39;</span><span style="color: #F8F8F2">, y: [</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">, </span><span style="color: #AE81FF">30</span><span style="color: #F8F8F2">, </span><span style="color: #F92672">-</span><span style="color: #AE81FF">60</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">], rotate: </span><span style="color: #AE81FF">360</span><span style="color: #F8F8F2">&#125;,</span></span>
<span class="line"><span style="color: #F8F8F2">                &#123;duration: </span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">, delay: </span><span style="color: #A6E22E">stagger</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">0.1</span><span style="color: #F8F8F2">), repeat: </span><span style="color: #AE81FF">Infinity</span><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">                   )</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">        &#125;</span></span>
<span class="line"><span style="color: #F8F8F2">    &lt;/</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">h1</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">use</span><span style="color: #F8F8F2">:animateText </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letters&quot;</span><span style="color: #F8F8F2">&gt; Example &lt;/</span><span style="color: #F92672">h1</span><span style="color: #F8F8F2">&gt;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-1knloha">Now we can even delete the entire loop block and use a single <code>h1</code> tag with text content and achieve the exact animation once again.</p> <p data-svelte-h="svelte-itllvi">We can also pass parameter to the action.
The color parameter will have a default of orangered in this example but we can also use a different value when applying the action.</p> <!-- HTML_TAG_START -->${`<pre class="shiki monokai" style="background-color: #272822" tabindex="0"><code><span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #F92672">import</span><span style="color: #F8F8F2"> &#123;animate, stagger&#125; </span><span style="color: #F92672">from</span><span style="color: #F8F8F2"> </span><span style="color: #E6DB74">&#39;motion&#39;</span></span>
<span class="line"><span style="color: #F8F8F2">        </span><span style="color: #66D9EF; font-style: italic">function</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">animateText</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">element</span><span style="color: #F8F8F2">, &#123;</span><span style="color: #FD971F; font-style: italic">color</span><span style="color: #F8F8F2">&#125;</span><span style="color: #F92672">=</span><span style="color: #F8F8F2">&#123;color: </span><span style="color: #E6DB74">&#39;orangered&#39;</span><span style="color: #F8F8F2">&#125;)&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">            </span><span style="color: #66D9EF; font-style: italic">const</span><span style="color: #F8F8F2"> text </span><span style="color: #F92672">=</span><span style="color: #F8F8F2"> element.innerTexx.</span><span style="color: #A6E22E">trim</span><span style="color: #F8F8F2">().</span><span style="color: #A6E22E">split</span><span style="color: #F8F8F2">();</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            element.innerText </span><span style="color: #F92672">=</span><span style="color: #E6DB74">&#39;&#39;</span><span style="color: #F8F8F2">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            text.</span><span style="color: #A6E22E">forEach</span><span style="color: #F8F8F2">(</span><span style="color: #FD971F; font-style: italic">letter</span><span style="color: #66D9EF; font-style: italic">=&gt;</span><span style="color: #F8F8F2">&#123;</span></span>
<span class="line"><span style="color: #F8F8F2">                        element.innerHTML </span><span style="color: #F92672">+=</span><span style="color: #E6DB74">&#96;</span></span>
<span class="line"><span style="color: #E6DB74">                            &lt;span class=&quot;letter&quot;&gt;</span><span style="color: #F92672">$&#123;</span><span style="color: #F8F8F2">letter</span><span style="color: #F92672">&#125;</span><span style="color: #E6DB74">&lt;/span&gt;</span></span>
<span class="line"><span style="color: #E6DB74">                        &#96;</span></span>
<span class="line"><span style="color: #F8F8F2">                    &#125;)</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">            </span><span style="color: #A6E22E">animate</span><span style="color: #F8F8F2">(</span></span>
<span class="line"><span style="color: #F8F8F2">                element.children,</span></span>
<span class="line"><span style="color: #F8F8F2">                </span><span style="color: #88846F">//[...element.children], //for typescript</span></span>
<span class="line"><span style="color: #F8F8F2">                &#123;color, y: [</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">, </span><span style="color: #AE81FF">30</span><span style="color: #F8F8F2">, </span><span style="color: #F92672">-</span><span style="color: #AE81FF">60</span><span style="color: #F8F8F2">,</span><span style="color: #AE81FF">0</span><span style="color: #F8F8F2">], rotate: </span><span style="color: #AE81FF">360</span><span style="color: #F8F8F2">&#125;,</span></span>
<span class="line"><span style="color: #F8F8F2">                &#123;duration: </span><span style="color: #AE81FF">1</span><span style="color: #F8F8F2">, delay: </span><span style="color: #A6E22E">stagger</span><span style="color: #F8F8F2">(</span><span style="color: #AE81FF">0.1</span><span style="color: #F8F8F2">), repeat: </span><span style="color: #AE81FF">Infinity</span><span style="color: #F8F8F2">&#125;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">                   )</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">        &#125;</span></span>
<span class="line"><span style="color: #F8F8F2">    &lt;/</span><span style="color: #F92672">script</span><span style="color: #F8F8F2">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F8F8F2">    &lt;</span><span style="color: #F92672">h1</span><span style="color: #F8F8F2"> </span><span style="color: #F92672">use</span><span style="color: #F8F8F2">:animateText=</span><span style="color: #F92672">&#123;</span><span style="color: #F8F8F2">&#123;color: </span><span style="color: #E6DB74">&#39;red&#39;</span><span style="color: #F8F8F2">&#125;</span><span style="color: #F92672">&#125;</span><span style="color: #F8F8F2"> </span><span style="color: #A6E22E">class</span><span style="color: #F8F8F2">=</span><span style="color: #E6DB74">&quot;letters&quot;</span><span style="color: #F8F8F2">&gt; Example &lt;/</span><span style="color: #F92672">h1</span><span style="color: #F8F8F2">&gt;</span></span></code></pre>`}<!-- HTML_TAG_END --> <p data-svelte-h="svelte-zqmd90">If you can grasp the concept of Svelte actions you can consider yourself a Svelte power user.</p>`;
  }
);
const __vite_glob_0_10 = /* @__PURE__ */ Object.freeze(
  /* @__PURE__ */ Object.defineProperty(
    {
      __proto__: null,
      default: Usingu20jsu20librariesu20withu20svelte,
      metadata
    },
    Symbol.toStringTag,
    { value: 'Module' }
  )
);
export { __vite_glob_0_10 as _ };
